name: Test and Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"

    - name: Download dependencies
      run: go mod download

    - name: Run unit tests
      run: |
        go test ./internal/middleware ./internal/repository ./pkg/kinopoisk ./pkg/youtube -v -cover
